genome:
    chrsizes : ../genome/S_cerevisiae.R64-2-1.chrsizes.tsv
    #transcripts : ../genome/annotations/Scer_polIItranscripts-adjustedTSS.bed
    #orfs : ../genome/annotations/Scer_nondubious_ORFs.bed
    prefix : "Scer_"

tss-upstr-dist: 200 #distance upstream of TSS peaks to look for overlapping nexus peaks

tss:
    peaks-path: ../tss-seq/peakcalling/
    coverage: ../tss-seq/coverage/
    diffexp-path: ../tss-seq/diff_exp/
    norm: spikenorm
nexus:
    peaks-path: ../chipnexus-tfiib/peakcalling/macs/
    coverage: ../chipnexus-tfiib/coverage/
    diffexp-path: ../chipnexus-tfiib/diff_binding/
    norm: libsizenorm

conditions:
    - diamide
    - spt6-37
controls:
    - YPD
    - WT-37

heatmaps:
    upstream: 300
    downstream: 100
    binsize: 10
    binstat: mean
    pct_cutoff: 0.97
    colormap: inferno

threads: 1
