genome:
    fasta : ../genome/S_cerevisiae.R64-2-1.fa
    annotation_workflow: ../build-annotations-cerevisiae/
    transcripts : ../genome/annotations/Scer_polIItranscripts-adjustedTSS.bed
    orfs : ../genome/annotations/Scer_nondubious_ORFs.bed
    prefix: "Scer_"
    # genic_regions: ../genome/annotations/Scer_genic-regions.bed
    # conv_regions: ../genome/annotations/Scer_convergent-regions.bed
    # div_regions: ../genome/annotations/Scer_divergent-regions.bed
    # intergenic_regions: ../genome/annotations/Scer_intergenic-regions.bed

#distance in bp to search for corresponding features
#for TSS-seq, search is done for a TFIIB peak 5'-distance to 3' of the TSS-seq peak
#for TFIIB, search is done +/- distance
search-distance: 200

bin_size: 20
step_size: 10
background_quantile: 0.90
signal_cutoff: 0.081

roc_cutoffs:
    - 0
    - 0.01
    - 0.02
    - 0.03
    - 0.05
    - 0.06
    - 0.08
    - 0.10
    - 0.12
    - 0.13
    - 0.14
    - 0.15
    - 0.16
    - 0.18
    - 0.22
    - 0.30
    - 0.50
    - 1.00
    - 3.00

groups:
    WT-37C:
        tss_peaks:
            all: ../tss-seq/peakcalling/WT-37C/WT-37C_experimental-idrpeaks.narrowPeak
            genic: ../tss-seq/peakcalling/WT-37C/genic/WT-37C-experimental-idrpeaks-genic.narrowpeak
            intragenic: ../tss-seq/peakcalling/WT-37C/intragenic/WT-37C-experimental-idrpeaks-intragenic.narrowpeak
            antisense: ../tss-seq/peakcalling/WT-37C/antisense/WT-37C-experimental-idrpeaks-antisense.narrowpeak
            convergent: ../tss-seq/peakcalling/WT-37C/convergent/WT-37C-experimental-idrpeaks-convergent.narrowpeak
            divergent: ../tss-seq/peakcalling/WT-37C/divergent/WT-37C-experimental-idrpeaks-divergent.narrowpeak
            intergenic: ../tss-seq/peakcalling/WT-37C/intergenic/WT-37C-experimental-idrpeaks-intergenic.narrowpeak
        tss_coverage:
          - ../tss-seq/coverage/spikenorm/WT-37C-1_tss-seq-spikenorm-SENSE.bedgraph
          - ../tss-seq/coverage/spikenorm/WT-37C-2_tss-seq-spikenorm-SENSE.bedgraph
        tfiib_peaks:
            all: ../chipnexus-tfiib/peakcalling/macs/WT-37C-Scer__peaks.narrowPeak
            genic: ../chipnexus-tfiib/peakcalling/macs/genic/WT-37C-exp-peaks-genic.tsv
            intragenic: ../chipnexus-tfiib/peakcalling/macs/intragenic/WT-37C-exp-peaks-intragenic.tsv
            intergenic: ../chipnexus-tfiib/peakcalling/macs/intergenic/WT-37C-exp-peaks-intergenic.tsv
        tfiib_coverage:
          - ../chipnexus-tfiib/coverage/libsizenorm/WT-37C-1_tfiib-chipnexus-libsizenorm-midpoints.bedgraph
          - ../chipnexus-tfiib/coverage/libsizenorm/WT-37C-2_tfiib-chipnexus-libsizenorm-midpoints.bedgraph
    spt6-1004-37C:
        tss_peaks:
            all: ../tss-seq/peakcalling/spt6-1004-37C/spt6-1004-37C_experimental-idrpeaks.narrowPeak
            genic: ../tss-seq/peakcalling/spt6-1004-37C/genic/spt6-1004-37C-experimental-idrpeaks-genic.narrowpeak
            intragenic: ../tss-seq/peakcalling/spt6-1004-37C/intragenic/spt6-1004-37C-experimental-idrpeaks-intragenic.narrowpeak
            antisense: ../tss-seq/peakcalling/spt6-1004-37C/antisense/spt6-1004-37C-experimental-idrpeaks-antisense.narrowpeak
            convergent: ../tss-seq/peakcalling/spt6-1004-37C/convergent/spt6-1004-37C-experimental-idrpeaks-convergent.narrowpeak
            divergent: ../tss-seq/peakcalling/spt6-1004-37C/divergent/spt6-1004-37C-experimental-idrpeaks-divergent.narrowpeak
            intergenic: ../tss-seq/peakcalling/spt6-1004-37C/intergenic/spt6-1004-37C-experimental-idrpeaks-intergenic.narrowpeak
        upregulated_tss_peaks:
            all: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-up.narrowpeak
            genic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/genic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-genic-up.narrowpeak
            intragenic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-up.narrowpeak
            antisense: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/antisense/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-antisense-up.narrowpeak
            convergent: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/convergent/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-convergent-up.narrowpeak
            divergent: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/divergent/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-divergent-up.narrowpeak
            intergenic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intergenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intergenic-up.narrowpeak
        tss_coverage:
          - ../tss-seq/coverage/spikenorm/spt6-1004-37C-1_tss-seq-spikenorm-SENSE.bedgraph
          - ../tss-seq/coverage/spikenorm/spt6-1004-37C-2_tss-seq-spikenorm-SENSE.bedgraph
        tfiib_peaks:
            all: ../chipnexus-tfiib/peakcalling/macs/spt6-1004-37C-Scer__peaks.narrowPeak
            genic: ../chipnexus-tfiib/peakcalling/macs/genic/spt6-1004-37C-exp-peaks-genic.tsv
            intragenic: ../chipnexus-tfiib/peakcalling/macs/intragenic/spt6-1004-37C-exp-peaks-intragenic.tsv
            intergenic: ../chipnexus-tfiib/peakcalling/macs/intergenic/spt6-1004-37C-exp-peaks-intergenic.tsv
        tfiib_coverage:
          - ../chipnexus-tfiib/coverage/libsizenorm/spt6-1004-37C-1_tfiib-chipnexus-libsizenorm-midpoints.bedgraph
          - ../chipnexus-tfiib/coverage/libsizenorm/spt6-1004-37C-2_tfiib-chipnexus-libsizenorm-midpoints.bedgraph
    # diamide:
    #     tss_peaks:
    #         all: ../tss-seq/peakcalling/diamide/diamide_experimental-idrpeaks.narrowPeak
    #         genic: ../tss-seq/peakcalling/diamide/genic/diamide-experimental-idrpeaks-genic.narrowpeak
    #         intragenic: ../tss-seq/peakcalling/diamide/intragenic/diamide-experimental-idrpeaks-intragenic.narrowpeak
    #         antisense: ../tss-seq/peakcalling/diamide/antisense/diamide-experimental-idrpeaks-antisense.narrowpeak
    #         convergent: ../tss-seq/peakcalling/diamide/convergent/diamide-experimental-idrpeaks-convergent.narrowpeak
    #         divergent: ../tss-seq/peakcalling/diamide/divergent/diamide-experimental-idrpeaks-divergent.narrowpeak
    #         intergenic: ../tss-seq/peakcalling/diamide/intergenic/diamide-experimental-idrpeaks-intergenic.narrowpeak
    #     upregulated_tss_peaks:
    #         all: ../tss-seq/diff_exp/diamide-v-YPD/spikenorm/diamide-v-YPD_tss-seq-spikenorm-diffexp-results-up.narrowpeak
    #         genic: ../tss-seq/diff_exp/diamide-v-YPD/spikenorm/genic/diamide-v-YPD_tss-seq-spikenorm-diffexp-results-genic-up.narrowpeak
    #         intragenic: ../tss-seq/diff_exp/diamide-v-YPD/spikenorm/intragenic/diamide-v-YPD_tss-seq-spikenorm-diffexp-results-intragenic-up.narrowpeak
    #         antisense: ../tss-seq/diff_exp/diamide-v-YPD/spikenorm/antisense/diamide-v-YPD_tss-seq-spikenorm-diffexp-results-antisense-up.narrowpeak
    #         convergent: ../tss-seq/diff_exp/diamide-v-YPD/spikenorm/convergent/diamide-v-YPD_tss-seq-spikenorm-diffexp-results-convergent-up.narrowpeak
    #         divergent: ../tss-seq/diff_exp/diamide-v-YPD/spikenorm/divergent/diamide-v-YPD_tss-seq-spikenorm-diffexp-results-divergent-up.narrowpeak
    #         intergenic: ../tss-seq/diff_exp/diamide-v-YPD/spikenorm/intergenic/diamide-v-YPD_tss-seq-spikenorm-diffexp-results-intergenic-up.narrowpeak
    #     tss_coverage:
    #       - ../tss-seq/coverage/spikenorm/diamide-1_tss-seq-spikenorm-SENSE.bedgraph
    #       - ../tss-seq/coverage/spikenorm/diamide-2_tss-seq-spikenorm-SENSE.bedgraph
    #     tfiib_peaks:
    #         all: ../chipnexus-tfiib/peakcalling/macs/diamide-Scer__peaks.narrowPeak
    #         genic: ../chipnexus-tfiib/peakcalling/macs/genic/diamide-exp-peaks-genic.tsv
    #         intragenic: ../chipnexus-tfiib/peakcalling/macs/intragenic/diamide-exp-peaks-intragenic.tsv
    #         intergenic: ../chipnexus-tfiib/peakcalling/macs/intergenic/diamide-exp-peaks-intergenic.tsv
    #     tfiib_coverage:
    #       - ../chipnexus-tfiib/coverage/libsizenorm/diamide-1_tfiib-chipnexus-libsizenorm-midpoints.bedgraph
    #       - ../chipnexus-tfiib/coverage/libsizenorm/diamide-2_tfiib-chipnexus-libsizenorm-midpoints.bedgraph
    # YPD:
    #     tss_peaks:
    #         all: ../tss-seq/peakcalling/YPD/YPD_experimental-idrpeaks.narrowPeak
    #         genic: ../tss-seq/peakcalling/YPD/genic/YPD-experimental-idrpeaks-genic.narrowpeak
    #         intragenic: ../tss-seq/peakcalling/YPD/intragenic/YPD-experimental-idrpeaks-intragenic.narrowpeak
    #         antisense: ../tss-seq/peakcalling/YPD/antisense/YPD-experimental-idrpeaks-antisense.narrowpeak
    #         convergent: ../tss-seq/peakcalling/YPD/convergent/YPD-experimental-idrpeaks-convergent.narrowpeak
    #         divergent: ../tss-seq/peakcalling/YPD/divergent/YPD-experimental-idrpeaks-divergent.narrowpeak
    #         intergenic: ../tss-seq/peakcalling/YPD/intergenic/YPD-experimental-idrpeaks-intergenic.narrowpeak
    #     tss_coverage:
    #       - ../tss-seq/coverage/spikenorm/YPD-1_tss-seq-spikenorm-SENSE.bedgraph
    #       - ../tss-seq/coverage/spikenorm/YPD-2_tss-seq-spikenorm-SENSE.bedgraph
    #     tfiib_peaks:
    #         all: ../chipnexus-tfiib/peakcalling/macs/YPD-Scer__peaks.narrowPeak
    #         genic: ../chipnexus-tfiib/peakcalling/macs/genic/YPD-exp-peaks-genic.tsv
    #         intragenic: ../chipnexus-tfiib/peakcalling/macs/intragenic/YPD-exp-peaks-intragenic.tsv
    #         intergenic: ../chipnexus-tfiib/peakcalling/macs/intergenic/YPD-exp-peaks-intergenic.tsv
    #     tfiib_coverage:
    #       - ../chipnexus-tfiib/coverage/libsizenorm/YPD-1_tfiib-chipnexus-libsizenorm-midpoints.bedgraph
    #       - ../chipnexus-tfiib/coverage/libsizenorm/YPD-2_tfiib-chipnexus-libsizenorm-midpoints.bedgraph

comparisons:
    spt6-1004-37C: WT-37C
    # diamide: YPD
    #

diff_exp_and_binding:
    spt6-1004-37C:
        WT-37C: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-all.narrowpeak

tfiib_counts:
    spt6-1004-37C-1:
        path: ../chipnexus-tfiib/coverage/counts/spt6-1004-37C-1_tfiib-chipnexus-counts-midpoints.bedgraph
        group: spt6-1004-37C
    spt6-1004-37C-2:
        path: ../chipnexus-tfiib/coverage/counts/spt6-1004-37C-2_tfiib-chipnexus-counts-midpoints.bedgraph
        group: spt6-1004-37C
    WT-37C-1:
        path: ../chipnexus-tfiib/coverage/counts/WT-37C-1_tfiib-chipnexus-counts-midpoints.bedgraph
        group: WT-37C
    WT-37C-2:
        path: ../chipnexus-tfiib/coverage/counts/WT-37C-2_tfiib-chipnexus-counts-midpoints.bedgraph
        group: WT-37C

# heatmaps:
#     upstream: 300
#     downstream: 100
#     binsize: 10
#     binstat: mean
#     pct_cutoff: 0.97
#     colormap: inferno

# threads: 1
