---
tss_workflow: ../tss-seq/
nexus_workflow: ../chipnexus-tfiib/
tfiib_workflow: ../chipnexus-tfiib-custom-analysis/
annotation_workflow: ../build-annotations-cerevisiae/

spike_in_normalization:
    tss: True
    tfiib: False

tss_vs_tfiib_comparisons:
    spt6-1004-37C: WT-37C
    diamide: YPD

#distance in bp to search for corresponding features
#for TSS-seq, search is done for a TFIIB peak 5'-distance to 3' of the TSS-seq peak
#for TFIIB, search is done +/- distance
search_distance: 200

window_size: 200

fdr_cutoff_tss: 0.1
fdr_cutoff_tfiib: 0.1
